#!/bin/bash

dellAcept="n"
folderUninstallDeleting=0
delDownloadsDir=0

workdir=/data/data/com.termux/files/home/storage/downloads/Nodes

ver="1.0"
workingWithNodesExtractorVer="4.9_beta"

echo "Unistalling script launched!"
read -p "You seriously want to delete script? (y/n) " dellAcept
if [ "$dellAcept" = "n" ]
then
	echo "You scared me!"
	echo "Dont do this again!"
	echo "Bye"
	exit
fi
if [ "$dellAcept" = "y" ]
then
	echo "Arrg, okay..."
	echo "The folder, where 'uninstall' file is located, will be deleted."
	read -p "Continue? (y/n) " folderUninstallDeleting

	if [ "$folderUninstallDeleting" = 'n' ]
	then
		echo "Ok... Move important files and come bacck soon!"
		exit
	fi
	if [ "$folderUninstallDeleting" = "y" ]
	then
		echo "Okay... Lets move."
		read -p "Delete 'sdcard/Downloads/Nodes' directory? (y/n) " delDownloadsDir
		if [ "$delDownloadsDir" = "n" ]
		then
			echo "Ok. Lets do this."
			echo "Deleting..."
			curdir=`pwd`
			rm -rf "$curdir"
			echo "Dir '$curdir'..."
			echo "Have a nice day, stranger"
			exit
		fi
		if [ "$delDownloadsDir" = "y" ]
		then
			echo "Ok. Lets do this."
			echo "Deleting..."
			curdir=`pwd`
			rm -rf "$curdir"
                        echo "Dir $curdir was deleted..."
			rm -rf "$workdir"
			echo "Dir $workdir was deleted..."
                        echo "Have a nice day, stranger"
                        exit
		else
			echo "Sorry, i cant understand what you mean"
			exit
                fi

	else
		echo "Sorry, im dont understanding you..."
	fi
else
	echo "Sorry, I dont understand..."
	exit
fi
